FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ./RPedretti.RazorComponents.Wasm.Sample ./RPedretti.RazorComponents.Wasm.Sample
COPY ./RPedretti.RazorComponents.Sample.Shared ./RPedretti.RazorComponents.Sample.Shared
RUN dotnet restore "RPedretti.RazorComponents.Wasm.Sample/RPedretti.RazorComponents.Wasm.Sample.csproj"
RUN dotnet build "RPedretti.RazorComponents.Wasm.Sample/RPedretti.RazorComponents.Wasm.Sample.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "RPedretti.RazorComponents.Wasm.Sample/RPedretti.RazorComponents.Wasm.Sample.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/RPedretti.RazorComponents.Wasm.Sample/dist .
COPY --from=publish /app/publish/wwwroot .
COPY RPedretti.RazorComponents.Wasm.Sample/Docker/nginx.conf /etc/nginx/nginx.conf